name: Write-Good

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  write_good:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install write-good
        run: npm install write-good -g

      - name: Run write-good
        run: |
          find . -name '*.md' -exec write-good {} +
